### ISSUE TITLE
Invalid order signature to avoid ABA problem after a successful buy

### ISSUE THREAD

**Issue by toshtoss** [ethscriptions-protocol/Bug-Competition#3]
Let's say:

Bob deposits an inscription A and then provides a signature SA (listingId:1, startDate: 7/21, endDate: 8/01).
Alice buys this inscription on 7/25.
Bob buys back this inscription on 7/30 but decides to sell it at a higher price, so he deposits inscription A again.

The problem is that since the signature SA is still valid, someone may use that signature to buy this inscription at the previous price.

Therefore, I suggest putting this listing ID into the cancel list to invalidate this signature after a successful buy.

**Comment by RogerPodacter** [comment]
Thank you!

I believe we account for this by invalidating all old listings whenever an ethscription is withdrawn in [this line of code](https://github.com/ethscriptions-protocol/Bug-Competition/blob/main/contracts/EthscriptionsMarketV3.sol#L156). Does this make sense? Or did we miss something?

**Comment by RogerPodacter** [comment]
(Not just withdrawn but transferred in any way actually)

**Comment by toshtoss** [comment]
yeah, that make sense, but where? i couldn't find it lol.  function _transferEthscription, or more precisely _afterTransferEthscription function only remove the deposit record correct me if im wrong.

**Comment by RogerPodacter** [comment]
The idea is that:

1. Buying triggers a [`_transferEthscription`](https://github.com/ethscriptions-protocol/Bug-Competition/blob/main/contracts/EthscriptionsMarketV3.sol#L138).

2. `_transferEthscription` calls [`_afterTransferEthscription`](https://github.com/ethscriptions-protocol/Bug-Competition/blob/main/contracts/EthscriptionsEscrower.sol#L49)

3. `_afterTransferEthscription` on the base escrow contract is overridden on the marketplace contract [here](https://github.com/ethscriptions-protocol/Bug-Competition/blob/main/contracts/EthscriptionsMarketV3.sol#L155). The override does `s().userListingsOfEthscriptionValidAfterTime[previousOwner][ethscriptionId] = block.timestamp` which will invalidate all old listings since listings must start before the purchase time for them to be valid in the first place. In your example, this value would be set to 7/25.

4. The overridden function now calls `super` which removes the deposit record.

In your example, if Alice (or anyone) tries to use signature SA again to buy from Bob, the buy function will check "does the signature specify a listing whose start time after `s().userListingsOfEthscriptionValidAfterTime[Bob][ethscriptionId]`?" and since the sig's start time is 7/21 and the valid after time is 7/25 the buy will fail.

Does this make sense? Or am I missing something here.

Thanks!
